### ISSUE TITLE
graphql-auth build failed

### ISSUE THREAD

**Issue by smartnet-club** [prisma/prisma-examples#980]
build failed with @prisma/photon@0.2.177
(works well with @prisma/photon@0.2.170)

node_modules/nexus-prisma/dist/dmmf/transformer.d.ts:2:22 - error TS7016: Could not find a declaration file for module '@prisma/photon'. './server/node_modules/@prisma/photon/index.j
s' implicitly has an 'any' type.
  Try `npm install @types/prisma__photon` if it exists or add a new declaration (.d.ts) file containing `declare module '@prisma/photon';`

2 import { DMMF } from '@prisma/photon';
                       ~~~~~~~~~~~~~~~~

  "dependencies": {
    "bcryptjs": "^2.4.3",
    "graphql": "^14.5.8",
    "graphql-shield": "5.7.3",
    "graphql-yoga": "1.18.3",
    "jsonwebtoken": "8.5.1",
    "nexus": "0.12.0-rc.4",
    "nexus-prisma": "0.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.7.1",
    "@babel/preset-typescript": "^7.7.2",
    "@prisma/sdk": "0.0.32",
    "@types/bcryptjs": "2.4.2",
    "@types/jsonwebtoken": "8.3.5",
    "@types/node": "12.12.8",
    "@types/ws": "6.0.3",
    "prisma2": "2.0.0-preview016.2",
    "ts-node": "8.5.2",
    "ts-node-dev": "1.0.0-pre.44",
    "typescript": "3.7.2"
  },

**Comment by FrancoisVeauvy** [comment]
I have a similar issue.

**Comment by martonlanga** [comment]
Installing this version of nexus somehow works for me:
`"nexus": "0.12.0-beta.14"`

**Comment by nikolasburk** [comment]
Hey @smartnet-club 👋 thanks a lot for opening this issue, this should be fixed now. Feel free to reopen the issue if you're still seeing the error 🙂
